/*
  MusicXML Library
  Copyright (C) Grame 2006-2013

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Grame Research Laboratory, 11, cours de Verdun Gensoul 69002 Lyon - France
  research@grame.fr
*/

#include <iomanip>      // setw, setprecision, ...
#include <cmath>
#include <string>

#include "xml2brlOah2ManPageGenerator.h"

#include "setTraceOahIfDesired.h"
#ifdef TRACE_OAH
  #include "traceOah.h"
#endif

#include "oahOah.h"

#include "version.h"

using namespace std;

namespace MusicXML2
{

//________________________________________________________________________
S_xml2brlOah2ManPageGenerator xml2brlOah2ManPageGenerator::create (
  const S_oahHandler handler,
  indentedOstream&   logOstream,
  ostream&           manPageOutputStream)
{
  xml2brlOah2ManPageGenerator* o = new
    xml2brlOah2ManPageGenerator (
      handler,
      logOstream,
      manPageOutputStream);
  assert(o!=0);
  return o;
}

xml2brlOah2ManPageGenerator::xml2brlOah2ManPageGenerator (
  const S_oahHandler handler,
  indentedOstream&   logOstream,
  ostream&            manPageOutputStream)
    : basicOah2ManPageGenerator (
      handler,
      logOstream,
      manPageOutputStream)
{}

xml2brlOah2ManPageGenerator::~xml2brlOah2ManPageGenerator ()
{}

//________________________________________________________________________
void xml2brlOah2ManPageGenerator::visitTheHandler ()
{
  fLogOutputStream <<
    ".\\\" DO NOT MODIFY THIS FILE!  It was generated by " <<
    gOahOah->fHandlerExecutableName <<
    " " <<
    currentVersionNumber () <<
    endl;

  if (fVisitedOahHandler) {
    // browse the visited oahHandler
    oahBrowser<oahHandler> browser (this);
    browser.browse (*fVisitedOahHandler);
  }
}

//________________________________________________________________________
void xml2brlOah2ManPageGenerator::visitStart (S_xml2brlVersionOahAtom& elt)
{
#ifdef TRACE_OAH
  if (gOahOah->fTraceOahVisitors) {
    fLogOutputStream <<
      endl <<
      ".\\\" --> Start visiting xml2brlVersionOahAtom" <<
      " \"" << elt->fetchNames () << "\"" <<
      endl;
  }
#endif

  fLogOutputStream <<
    "\\fB\\-" <<
    replaceSubstringInString (elt->getShortName (), "-", "\\-") <<
    "\\fR, " <<
    "\\fB\\-" <<
    replaceSubstringInString (elt->getLongName (), "-", "\\-") <<
    "\\fR, " <<
    elt->fetchNamesBetweenParentheses () <<
    endl <<

    ".IP" <<
    endl <<
    elt->getDescription () <<
    endl;
}

//________________________________________________________________________
void xml2brlOah2ManPageGenerator::visitStart (S_xml2brlAboutOahAtom& elt)
{
#ifdef TRACE_OAH
  if (gOahOah->fTraceOahVisitors) {
    fLogOutputStream <<
      endl <<
      ".\\\" --> Start visiting xml2brlAboutOahAtom" <<
      " \"" << elt->fetchNames () << "\"" <<
      endl;
  }
#endif

  fLogOutputStream <<
    ".HP" <<
    endl <<
    "\\fB\\-" <<
    replaceSubstringInString (elt->getShortName (), "-", "\\-") <<
    "\\fR, " <<
    "\\fB\\-" <<
    replaceSubstringInString (elt->getLongName (), "-", "\\-") <<
    "\\fR, " <<
    endl <<

    ".IP" <<
    endl <<
    elt->getDescription () <<
    endl;
}

//________________________________________________________________________
void xml2brlOah2ManPageGenerator::visitStart (S_xml2brlContactOahAtom& elt)
{
#ifdef TRACE_OAH
  if (gOahOah->fTraceOahVisitors) {
    fLogOutputStream <<
     endl <<
      ".\\\" --> Start visiting xml2brlContactOahAtom" <<
      " \"" << elt->fetchNames () << "\"" <<
      endl;
  }
#endif

  fLogOutputStream <<
    ".HP" <<
    endl <<
    "\\fB\\-" <<
    replaceSubstringInString (elt->getShortName (), "-", "\\-") <<
    "\\fR, " <<
    "\\fB\\-" <<
    replaceSubstringInString (elt->getLongName (), "-", "\\-") <<
    "\\fR, " <<
    endl <<

    ".IP" <<
    endl <<
    elt->getDescription () <<
    endl;
}


} // namespace
